sudo: false

services:
  - mongodb
  - redis-server

language: node_js
node_js:
  - "4"
  - "6"
  - "8"
  - "10"
  - "12"
  - "14"

branches:
  only:
    - master

notifications:
  email:
    - adriano@raiano.ch
